import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import Script from "next/script";
import { QueryProvider } from "@/providers/QueryProvider/Provider";
import { AuthProvider } from "@/providers/AuthProvider/Provider";
import { ModelProvider } from "@/providers/ModelProvider/Provider";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="https://yastatic.net/s3/passport-sdk/autofill/v1/sdk-suggest-with-polyfills-latest.js"></Script>
        <Script src="https://accounts.google.com/gsi/client"></Script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QueryProvider>
          <AuthProvider>
            <ModelProvider>
              {children}
              {modal}
            </ModelProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
