import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/providers/AuthProvider/Provider";
import { ModelProvider } from "@/providers/ModelProvider/Provider";
import { QueryProvider } from "@/providers/QueryProvider/Provider";
import "./globals.scss";
import "./globals.css";
// import { fetchDummy } from "@/api";
// import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  // await fetchDummy((await cookies()).toString());

  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json"></link>
        <link
          rel="icon"
          href="/favicon.ico?favicon.ico"
          sizes="48x48"
          type="image/x-icon"
        ></link>
        <link
          rel="icon"
          href="/icon0.svg?icon0.svg"
          sizes="any"
          type="image/svg+xml"
        ></link>
        <link
          rel="icon"
          href="/icon1.png?icon1.png"
          sizes="96x96"
          type="image/png"
        ></link>
        <link
          rel="apple-touch-icon"
          href="/apple-icon.png?apple-icon.22c81a72.png"
          sizes="180x180"
          type="image/png"
        ></link>
        <meta name="apple-mobile-web-app-title" content="JonuAI" />
        <meta
          name="google-site-verification"
          content="kOMBcuVi1F7zH0Rj3nyl0v3HiIyN2OUJwcvY99xFYpY"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QueryProvider>
          <AuthProvider>
            <ModelProvider>
              {children}
              {modal}
            </ModelProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
